name: Actualizar Precios

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Actualizar archivo precios.json
        run: |
          echo "$JSON_DATA" > data/precios.json

      - name: Commit y push
        run: |
          git config --global user.name "Irving Bot"
          git config --global user.email "irving@example.com"
          git add data/precios.json
          git commit -m "Actualización de precios automática"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
